---
name: "API Deployment"

on:
  workflow_call:
    inputs:
      environment:
        description: name of environment
        required: true
        type: string
      function:
        description: name of function
        required: true
        type: string
      function_url:
        description: URL of the function
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: API Deployment
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.function_url }}
    steps:
      - name: "Code checkout"
        uses: actions/checkout@v3
      - run: echo "${{ inputs.environment }} lambda updated."

  post-deployment-qa:
    needs: deploy
    uses: ./.github/workflows/post_deployment_qa.yml
    secrets: inherit

  post-deployment-dev:
    needs: 
      - post-deployment-qa
    uses: ./.github/workflows/post_deployment_dev.yml
    secrets: inherit

  post-deployment-uat:
    needs: 
      - post-deployment-dev
    uses: ./.github/workflows/post_deployment_uat.yml
    secrets: inherit
