---
name: DB migration

on:
  workflow_call:
  push:
    paths:
      - 'build/*'
jobs:
  migrate:
    runs-on: ubuntu-latest
    name: db migrate
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: migrate
        run: echo "migrating..."
