---
name: DB migration

on:
  workflow_call:
  push:
    paths:
      - 'build/*'
jobs:
  db-migrate:
    runs-on: ubuntu-latest
    name: db migrate
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - run: echo "migration complete"
