---
name: Post Deployment

on:
  workflow_run:
    workflows: ["db-migrate-dev"]
    types:
      - completed
  workflow_call:
jobs:
  verify-deployment-dev:
    runs-on: ubuntu-latest
    name: Verify deployed API
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - run: echo "post validation running...."
