---
name: Post Deployment

on:
  workflow_run:
    workflows: ["db-migrate-uat"]
    types:
      - completed
  workflow_call:
jobs:
  verify-deployment-uat:
    runs-on: ubuntu-latest
    name: Verify deployed API
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - run: echo "post validation running.... on UAT"
  
